import type { Env } from "../../env";
import type { KbDoc } from "../../kb/docs";
import type { MarketingDraft, MarketingFormat, MarketingLanguage, SavedMarketingDraft } from "../../marketing-compliance/copilot";
import { layout } from "./layout";

const esc = (s: string) => s.replace(/[&<>"']/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch]!));
const labels: Record<MarketingFormat, string> = { mls: "MLS", instagram: "Instagram", facebook: "Facebook", reel: "Reel", "open-house": "Open House", "meta-ad": "Meta Ads (Housing)" };

export function renderMarketingCopilot(env: Env, doc: KbDoc, result: MarketingDraft, selected: MarketingFormat = "instagram", selectedLanguage: MarketingLanguage = "es", saved?: SavedMarketingDraft, history: SavedMarketingDraft[] = []): string {
  const blocked = result.status === "requires_confirmation";
  const missing = result.missingFacts.length ? `<div style="border:1px solid var(--bad);background:rgba(217,122,106,.08);padding:13px;font-size:11px;color:var(--bad)"><b>Requiere confirmación del Realtor</b><ul style="margin:7px 0 0;padding-left:17px">${result.missingFacts.map(esc).map((f) => `<li>${f}</li>`).join("")}</ul><div style="color:var(--muted);margin-top:8px">El subagente no generará contenido ni completará esos datos.</div></div>` : "";
  const facts = Object.entries(result.fields).map(([key, value]) => `<div style="border-top:1px solid var(--line);padding:8px 0;font-size:11px"><span style="color:var(--dim)">${esc(key)}</span><br><span style="color:var(--cream)">${esc(value || "No confirmado")}</span></div>`).join("");
  const draft = result.draft ? `<section style="border:1px solid var(--line);background:var(--panel);padding:16px"><div style="display:flex;justify-content:space-between;gap:8px"><div style="font-size:10px;letter-spacing:.14em;color:var(--accent)">BORRADOR PARA REVISIÓN</div>${saved ? `<span style="font-size:10px;color:var(--dim)">Guardado como borrador</span>` : ""}</div><pre style="white-space:pre-wrap;font:12px/1.6 system-ui;color:var(--cream);margin:10px 0 0">${esc(result.draft)}</pre>${saved ? `<form method="post" action="/admin/marketing/drafts/${encodeURIComponent(saved.id)}/status" style="margin-top:12px;display:flex;gap:8px"><button name="status" value="approved" class="ghostbtn" style="padding:7px 9px;font-size:10px">Aprobar para publicar manualmente</button><button name="status" value="archived" class="ghostbtn" style="padding:7px 9px;font-size:10px">Archivar</button></form>` : ""}</section>` : "";
  const historyHtml = history.length ? `<section style="border:1px solid var(--line);background:var(--panel);padding:14px"><div style="font-size:10px;letter-spacing:.12em;color:var(--accent);margin-bottom:8px">HISTORIAL DE BORRADORES</div>${history.map((item) => `<div style="border-top:1px solid var(--line);padding:9px 0;font-size:11px"><b>${labels[item.format]}</b> · <span style="color:${item.status === "approved" ? "var(--ok)" : item.status === "archived" ? "var(--dim)" : "var(--accent)"}">${item.status === "approved" ? "Aprobado" : item.status === "archived" ? "Archivado" : "Borrador"}</span><div style="color:var(--muted);margin-top:3px">${esc(item.content.slice(0, 140))}${item.content.length > 140 ? "…" : ""}</div></div>`).join("")}</section>` : "";
  const generator = `<section style="border:1px solid var(--line);background:var(--panel);padding:16px"><form method="post" action="/admin/marketing/${encodeURIComponent(doc.id)}" style="display:grid;gap:12px"><label style="font-size:11px;color:var(--muted)">Formato de borrador<select name="format" style="display:block;margin-top:6px;width:100%;background:var(--bg);color:var(--cream);border:1px solid var(--line);padding:9px">${(Object.keys(labels) as MarketingFormat[]).map((key) => `<option value="${key}" ${selected === key ? "selected" : ""}>${labels[key]}</option>`).join("")}</select></label><label style="font-size:11px;color:var(--muted)">Idioma<select name="language" style="display:block;margin-top:6px;width:100%;background:var(--bg);color:var(--cream);border:1px solid var(--line);padding:9px"><option value="es" ${selectedLanguage === "es" ? "selected" : ""}>Español</option><option value="en" ${selectedLanguage === "en" ? "selected" : ""}>English</option></select></label><button ${blocked ? "disabled" : ""} class="bigbtn" style="padding:10px;background:${blocked ? "var(--line)" : "var(--accent)"};border:1px solid var(--line);color:#10130e;font-weight:700;cursor:${blocked ? "not-allowed" : "pointer"}">GENERAR BORRADOR</button></form></section>`;
  const body = `<div style="display:flex;flex-direction:column;gap:16px"><a href="/admin/kb" style="font-size:11px">← Volver a Market Intel</a><section style="border:1px solid var(--line);background:linear-gradient(135deg,var(--panel),var(--panel2));padding:18px"><div style="font-size:10px;letter-spacing:.16em;color:var(--accent)">SUBAGENTE INDEPENDIENTE</div><h2 style="font-family:'Space Grotesk';font-size:23px;margin:6px 0">Marketing Compliance Copilot</h2><p style="font-size:12px;color:var(--muted);max-width:690px;margin:0">Solo trabaja con esta ficha verificada. No responde WhatsApp, Instagram ni Messenger; tampoco publica contenido. Si falta un hecho, lo deja pendiente de confirmación.</p></section><div style="display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:14px"><div style="display:grid;gap:14px">${draft}${generator}${historyHtml}</div><aside style="border:1px solid var(--line);background:var(--panel);padding:14px"><div style="font-size:10px;letter-spacing:.12em;color:var(--accent)">HECHOS FUENTE</div>${facts}</aside></div>${missing}<section style="border:1px solid var(--line);background:var(--panel2);padding:12px;font-size:10.5px;color:var(--muted)">${result.complianceFlags.map(esc).join("<br>")}</section></div>`;
  return layout({ title: "Marketing Copilot", activeTab: "kb", body, env });
}
