import type { Env } from "./env";
import { Db } from "./db/client";
import { LeadsRepo } from "./db/leads";
import { RealtorRepo } from "./db/realtor";
import { layout } from "./admin/views/layout";

const esc = (value: unknown) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const openHouseUrl = (env: Env, token: string) => `${env.DASHBOARD_BASE_URL.replace(/\/$/, "")}/open-house/${encodeURIComponent(token)}`;

export interface OpenHouse { id: string; token: string; title: string; address: string; scheduled_at: number | null; status: "open" | "offers" | "closed"; created_at: number; updated_at: number; }

export async function renderOpenHouses(env: Env, prefill?: { title?: string; address?: string }): Promise<string> {
  const db = new Db(env.DB);
  const homes = await db.all<OpenHouse & { visitors: number; due: number }>(
    `SELECT h.*, COUNT(v.id) visitors, SUM(CASE WHEN v.contacted_at IS NULL AND v.followup_due_at <= ? THEN 1 ELSE 0 END) due
     FROM open_houses h LEFT JOIN open_house_visitors v ON v.open_house_id = h.id
     GROUP BY h.id ORDER BY COALESCE(h.scheduled_at, h.created_at) DESC`, [Date.now()],
  );
  const cards = homes.map((home) => {
    const url = openHouseUrl(env, home.token);
    const qr = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(url)}`;
    const status = home.status === "offers" ? "Ofertas recibidas" : home.status === "closed" ? "Cerrado" : "Abierto";
    const statusColor = home.status === "offers" ? "var(--accent)" : home.status === "closed" ? "var(--dim)" : "var(--info)";
    return `<article class="card" style="border:1px solid var(--line);background:var(--panel);padding:16px;display:grid;grid-template-columns:116px minmax(0,1fr);gap:16px"><a href="${qr}" target="_blank" rel="noreferrer" title="Abrir QR para imprimir"><img src="${qr}" width="112" height="112" alt="QR ${esc(home.address)}" style="display:block;background:white;padding:5px;width:112px;height:112px"></a><div style="min-width:0"><div style="display:flex;justify-content:space-between;gap:10px;align-items:start"><div><div style="font-family:'Space Grotesk';font-weight:700;font-size:17px">${esc(home.title)}</div><div style="font-size:11px;color:var(--muted);margin-top:3px">${esc(home.address)}</div></div><span style="font-size:9px;letter-spacing:.1em;border:1px solid ${statusColor};color:${statusColor};padding:3px 6px;white-space:nowrap">${status}</span></div><div style="display:flex;gap:14px;flex-wrap:wrap;margin:13px 0;font-size:11px"><span><b style="color:var(--accent)">${home.visitors}</b> registros</span><span><b style="color:${home.due ? "var(--accent)" : "var(--cream)"}">${home.due}</b> follow-ups listos</span>${home.scheduled_at ? `<span style="color:var(--dim)">${new Date(home.scheduled_at).toLocaleString("es-US")}</span>` : ""}</div><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="ghostbtn" href="${url}" target="_blank" rel="noreferrer" style="padding:7px 9px;font-size:10px">Abrir registro →</a><a class="ghostbtn" href="/admin/open-houses/${encodeURIComponent(home.id)}" style="padding:7px 9px;font-size:10px">Ver visitantes →</a><form method="post" action="/admin/open-houses/${encodeURIComponent(home.id)}/status"><select name="status" onchange="this.form.submit()" style="background:var(--bg);border:1px solid var(--line);color:var(--cream);padding:7px;font-size:10px"><option value="open" ${home.status === "open" ? "selected" : ""}>Abierto</option><option value="offers" ${home.status === "offers" ? "selected" : ""}>Con ofertas</option><option value="closed" ${home.status === "closed" ? "selected" : ""}>Cerrado</option></select></form></div></div></article>`;
  }).join("") || `<div style="padding:34px;text-align:center;color:var(--dim);font-size:12px">Crea el primer Open House para generar su QR único.</div>`;
  const title = prefill?.title?.slice(0, 120) || "";
  const address = prefill?.address?.slice(0, 180) || "";
  const sourceNotice = address ? `<div style="font-size:10px;color:var(--accent);margin-top:4px">Ficha verificada seleccionada: revisa fecha y genera su QR único.</div>` : "";
  const body = `<div style="display:flex;flex-direction:column;gap:18px"><section class="card" style="border:1px solid var(--line);background:linear-gradient(135deg,var(--panel),var(--panel2));padding:20px"><div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.7fr);gap:22px"><div><div style="font-size:10px;letter-spacing:.18em;color:var(--accent);text-transform:uppercase">Open House OS</div><h2 style="font-family:'Space Grotesk';font-size:25px;margin:6px 0">Cada propiedad, su QR y su seguimiento.</h2><p style="font-size:12px;line-height:1.55;color:var(--muted);max-width:620px">El QR abre un registro público de esa propiedad. Los visitantes, follow-ups y alertas de ofertas quedan separados por listing para no cruzar mensajes.</p></div><form method="post" action="/admin/open-houses" style="border:1px solid var(--line);background:var(--bg);padding:14px;display:grid;gap:8px"><b style="font-size:12px">Crear Open House</b><input name="title" required maxlength="120" value="${esc(title)}" placeholder="Ej. Open House · 7993 W 18th Ln" style="padding:9px;background:var(--panel);border:1px solid var(--line);color:var(--cream)"><input name="address" required maxlength="180" value="${esc(address)}" placeholder="Dirección completa" style="padding:9px;background:var(--panel);border:1px solid var(--line);color:var(--cream)">${sourceNotice}<input name="scheduled_at" type="datetime-local" style="padding:9px;background:var(--panel);border:1px solid var(--line);color:var(--cream)"><button class="bigbtn" style="padding:10px;background:var(--accent);border:1px solid var(--accent);color:#10130e;font-weight:700;cursor:pointer">GENERAR QR ÚNICO</button></form></div></section><section style="display:grid;gap:12px">${cards}</section></div>`;
  return layout({ title: "Open Houses", activeTab: "openhouses", body, env });
}

export async function renderOpenHouseVisitors(env: Env, id: string): Promise<string> {
  const db = new Db(env.DB);
  const home = await db.first<OpenHouse>("SELECT * FROM open_houses WHERE id = ?", [id]);
  if (!home) return layout({ title: "Open House", activeTab: "openhouses", body: "<p>Propiedad no encontrada.</p>", env });
  const visitors = await db.all<{ id: string; name: string; phone: string; email: string | null; interest: string | null; created_at: number; followup_due_at: number; contacted_at: number | null }>("SELECT * FROM open_house_visitors WHERE open_house_id = ? ORDER BY created_at DESC", [id]);
  const body = `<div style="display:flex;flex-direction:column;gap:16px"><a href="/admin/open-houses" style="font-size:11px">← Todos los Open Houses</a><section class="card" style="border:1px solid var(--line);background:var(--panel);padding:18px"><div style="font-size:10px;letter-spacing:.16em;color:var(--accent)">VISITANTES POR PROPIEDAD</div><h2 style="font-family:'Space Grotesk';font-size:22px;margin:6px 0">${esc(home.title)}</h2><p style="font-size:12px;color:var(--muted);margin:0">${esc(home.address)} · Estado: ${home.status === "offers" ? "con ofertas" : home.status}</p></section><section style="display:grid;gap:8px">${visitors.map((v) => { const text = home.status === "offers" ? `Hola ${v.name}, quería avisarte que ${home.address} ya recibió ofertas. Si sigues interesado/a, responde a este mensaje para revisar tus próximos pasos.` : `Hola ${v.name}, gracias por visitar ${home.address}. ¿Qué duda te quedó de la propiedad?`; const wa = `https://wa.me/${v.phone.replace(/\D/g, "")}?text=${encodeURIComponent(text)}`; return `<article style="border:1px solid var(--line);background:var(--panel);padding:13px;display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><b style="font-size:13px">${esc(v.name)}</b><div style="font-size:10px;color:var(--muted);margin-top:4px">${esc(v.phone)}${v.email ? ` · ${esc(v.email)}` : ""}${v.interest ? ` · ${esc(v.interest)}` : ""}</div><div style="font-size:10px;color:${v.contacted_at ? "var(--ok)" : v.followup_due_at <= Date.now() ? "var(--accent)" : "var(--dim)"};margin-top:5px">${v.contacted_at ? "Seguimiento marcado" : v.followup_due_at <= Date.now() ? "Follow-up de 24h listo" : "Seguimiento programado"}</div></div><div style="display:flex;gap:7px"><a class="ghostbtn" href="${wa}" target="_blank" rel="noreferrer" style="padding:8px 9px;font-size:10px">Abrir WhatsApp</a><form method="post" action="/admin/open-houses/visitors/${v.id}/contacted"><button class="ghostbtn" style="padding:8px 9px;font-size:10px">Marcar contacto</button></form></div></article>`; }).join("") || `<div style="padding:32px;text-align:center;color:var(--dim);font-size:12px">Aún no hay registros para esta propiedad.</div>`}</section></div>`;
  return layout({ title: "Visitantes", activeTab: "openhouses", body, env });
}

export function renderPublicOpenHouse(home: OpenHouse, submitted = false): string {
  const notice = home.status === "offers" ? `<div style="border:1px solid #d9a441;background:#fff9e8;padding:11px;font-size:13px;color:#5e4816">Esta propiedad ya recibió ofertas. Regístrate si quieres recibir una actualización directa.</div>` : "";
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(home.title)} · Registro</title><style>body{margin:0;background:#f5f7f2;color:#182015;font:15px system-ui,sans-serif}main{max-width:560px;margin:0 auto;padding:32px 18px}.card{background:#fff;border:1px solid #d5dfca;padding:24px;box-shadow:5px 5px 0 #dce8cf}h1{font-size:28px;margin:8px 0}input,select{box-sizing:border-box;width:100%;padding:12px;border:1px solid #b8c7ac;margin-top:10px;font:inherit}button{width:100%;margin-top:14px;padding:13px;background:#bff549;border:1px solid #7ba820;color:#152000;font-weight:700;cursor:pointer}.eyebrow{font-size:11px;color:#60821c;letter-spacing:.14em;font-weight:700}${submitted ? ".form{display:none}" : ""}</style></head><body><main><div class="card"><div class="eyebrow">OPEN HOUSE · REGISTRO DE VISITA</div><h1>${esc(home.title)}</h1><p style="color:#52614c">${esc(home.address)}</p>${notice}${submitted ? `<h2>¡Gracias por registrarte!</h2><p>Tu interés quedó asociado únicamente a esta propiedad. El equipo te contactará con los próximos pasos.</p>` : `<form class="form" method="post"><input name="name" required maxlength="100" placeholder="Nombre completo"><input name="phone" required inputmode="tel" maxlength="40" placeholder="Teléfono / WhatsApp"><input name="email" type="email" maxlength="160" placeholder="Email (opcional)"><select name="interest"><option value="Quiero más información">Quiero más información</option><option value="Me interesa hacer oferta">Me interesa hacer oferta</option><option value="Quiero una visita privada">Quiero una visita privada</option></select><button>REGISTRAR MI VISITA</button></form>`}</div></main></body></html>`;
}

export async function registerOpenHouseVisitor(env: Env, home: OpenHouse, input: { name: string; phone: string; email?: string; interest?: string }): Promise<void> {
  const db = new Db(env.DB); const now = Date.now();
  const phone = input.phone.trim();
  const existing = await db.first<{ id: string }>("SELECT id FROM open_house_visitors WHERE open_house_id = ? AND phone = ?", [home.id, phone]);
  if (existing) return;
  const leadId = await new LeadsRepo(db).create({ conversationId: null, channelUserId: null, name: input.name.trim(), contact: phone, intent: `Open House · ${home.address}`, notes: `Registro Open House: ${input.interest || "más información"}`, metadata: { operation: "buyer", openHouseId: home.id, property: home.address, interest: input.interest || "más información" } });
  await new RealtorRepo(db).attachLead({ leadId, kind: "buyer", score: input.interest === "Me interesa hacer oferta" ? 65 : 45, reason: `Visitó Open House: ${home.address}`, source: "open-house-qr", nextAction: "Enviar seguimiento de Open House dentro de 24 horas.", tags: ["buyer", "open-house", input.interest === "Me interesa hacer oferta" ? "hot" : "warm"] });
  await db.run("INSERT INTO open_house_visitors (id, open_house_id, lead_id, name, phone, email, interest, created_at, followup_due_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [crypto.randomUUID(), home.id, leadId, input.name.trim(), phone, input.email?.trim() || null, input.interest?.trim() || null, now, now + 24 * 60 * 60 * 1000]);
}
